"""
Django settings for moviereviews project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# The three settings below all read from an environment variable first,
# falling back to the original hardcoded dev value if it's unset - so
# local development (manage.py runserver, no env vars set) behaves
# exactly as before, and only a deployment that explicitly sets these
# (e.g. PythonAnywhere's WSGI file - see deploy/pythonanywhere.md)
# changes anything. Never hand-edit these fallbacks to "production"
# values directly - that would defeat the point of DEBUG being off and
# a real secret key being used only where it's actually deployed.

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback here is the original `startproject`-generated key -
# fine for local dev (nothing sensitive relies on it), but a real
# deployment must override it via DJANGO_SECRET_KEY so this value never
# ends up protecting a live site (it's sitting in git history, so it
# can never be treated as secret again once anyone's seen this file).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-g!kkt%9xl#7-$yqo35iy$27+az0p6tk0k)=o&%fe&-d%*9*adt',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Comma-separated in the env var (e.g. "someuser.pythonanywhere.com") -
# split into the list Django expects. Empty/unset means an empty list,
# same as the original hardcoded value - harmless for local dev, since
# Django's runserver always allows localhost/127.0.0.1 regardless of
# ALLOWED_HOSTS when DEBUG=True.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

# HTTPS-only cookies/redirect - derived from DEBUG rather than its own
# env var, since there's no scenario here where DEBUG=False but the
# site isn't served over HTTPS (PythonAnywhere terminates HTTPS itself
# for *.pythonanywhere.com). Off for local dev (DEBUG=True, plain
# http://127.0.0.1), on for anything deployed with DEBUG=False - see
# `manage.py check --deploy`, which flags these by default otherwise.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'movie.apps.MovieConfig',  # movie listing/review app - see movie/apps.py
    'news.apps.NewsConfig',  # news listing app - see news/apps.py
    'accounts.apps.AccountsConfig',  # signup/login/logout - see accounts/apps.py
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'moviereviews.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moviereviews.wsgi.application'

# Where @login_required (used on movie/views.py's review CRUD views)
# sends an anonymous visitor, with a ?next=<original path> query string
# attached so accounts/views.py's loginuser() can send them back after
# logging in. 'login' is accounts/urls.py's name for '/accounts/login/'
# - which happens to already be Django's own *default* LOGIN_URL, but
# it's set explicitly here so that stays true even if the accounts
# app's routes ever move.
LOGIN_URL = 'login'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Where `manage.py collectstatic` gathers every app's static files
# (mainly the Django admin's own CSS/JS - this project has no custom
# static/ files of its own) into one folder, ready to hand off to a
# real web server. Only matters once DEBUG=False - Django's own
# dev server serves static files directly without this when DEBUG=True,
# which is why local dev has worked fine without it until now. See
# deploy/pythonanywhere.md for where this actually gets used.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded content, e.g. Movie.image) - distinct from
# STATIC_URL/STATIC_ROOT above, which is for this project's own
# CSS/JS/images. MEDIA_ROOT is where uploaded files are saved on disk;
# MEDIA_URL is the prefix used to build their public URLs. Serving
# these from Django itself (see moviereviews/urls.py) is only fine for
# local dev - a real deployment would serve them from a proper file
# host/CDN instead.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
